In [1]:
import torch
import torch.optim as optim
import torch.nn as nn
import numpy as np
import pandas as pd

In [2]:
from models import MYMODEL
from utils import load_data
from dataset import ODDataset
from config import get_configs

In [3]:
args = get_configs()

In [4]:
te,x,adj,y = load_data(args)

In [12]:
te[0][0]

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
y[0]

In [21]:
import torch

# 输入张量
tensor1 = torch.tensor([1, 1, 1, 1])
tensor2 = torch.tensor([3, 5])





In [22]:
tensor2 = torch.cat((torch.zeros_like(tensor2),tensor2))
tensor2

tensor([0, 0, 3, 5])

In [23]:
tensor = tensor1 + tensor2
tensor

tensor([1, 1, 4, 6])