In [1]:
import numpy as np
import pandas as pd

In [19]:
od_data = np.load('./data/NYTaxi/od_matrix.npy')
od_data[0][0]

array([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 2., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.])

In [32]:
od_data[0][1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
nytaxi_data = np.load('./data/NYTaxi/NYTaxi.npy').astype("int").reshape([-1, 3])
nytaxi_pd = pd.DataFrame(nytaxi_data)
# o_requried = nytaxi_pd[0].map(lambda x : x==62)
# d_required = nytaxi_pd[1].map(lambda x : x==48)
# nytaxi_pd[o_requried & d_required]
nytaxi_pd

0   1           2
0         62  11           1
1         48  32           5
2         20  13           6
3         36  43           9
4         53  62          11
...       ..  ..         ...
38498582  61  27   603751269
38498583  59  20   603755189
38498584  19  55   603755754
38498585   4  40  2179440942
38498586   3  37  2179441539

[38498587 rows x 3 columns]

In [31]:

z = pd.to_datetime(2179441539, unit='s')
z

Timestamp('2039-01-24 00:25:39')

In [34]:
sample_data = np.load('./data/sampled.npy')
sample_data

array([[    62,     11,      1],
       [    48,     32,      5],
       [    20,     13,      6],
       ...,
       [    59,     54, 604796],
       [     8,     10, 604797],
       [    18,     46, 604798]])